### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by sachinsawant71** [feathers-plus/feathers-authentication-management#102]
I tried to install the package using command -
npm install @feathers-plus/authentication-management

I am getting error following error - 

```
npm ERR! code E404
npm ERR! 404 Not Found: @feathers-plus/authentication-management@latest
```

### System configuration
**NodeJS version**:  v8.9.0

**Operating System**: Windows

**Browser Version**: Chrome 

**Module Loader**: npm v5.5.1

**Comment by oussamaABID** [comment]
npm install "feathers-authentication-management"
