### ISSUE TITLE
Can't provide custom hashPassword function

### ISSUE THREAD

**Issue by zhouanbo** [feathers-plus/feathers-authentication-management#109]
A feature request that make hashPassword function customizable. Also the 'user' param in notifier doesn't allow configuring the name of password field to exclude in the response.

**Comment by eddyystop** [comment]
The hashing and compare functions have been moved out of the repo in the authentication-local-management rewrite of this repo.

**Comment by eddyystop** [comment]
The password field is now both customizable and inherited from config/default.json in a-l-m. Full details at https://github.com/feathers-plus/authentication-local-management/blob/master/misc/upgrading.md

Please make any comments in a-l-m
