### ISSUE TITLE
Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by koraniar** [feathers-plus/feathers-authentication-management#117]
### Steps to reproduce

I am trying to send reset password email, here is my code
```
    const users = await this.app.service('user').find({
      query: { email: data.email },
      paginate: false
    });

    if (users && users.length === 1) {
      const email = users[0].email;

      let options = {
        action: 'sendResetPwd',
        value: { email }
      }
  
      let [err, result] = await this.app.service('authManagement').create(options)
    }
```

but I get the next error
```
error:  message=Cannot read property 'id' of undefined, stack=TypeError: Cannot read property 'id' of undefined
    at sendResetPwd (/Users/koraniar/GitHub/Vtul/vtul-api/node_modules/feathers-authentication-management/lib/sendResetPwd.js:21:27)
    at Object.create (/Users/koraniar/GitHub/Vtul/vtul-api/node_modules/feathers-authentication-management/lib/service.js:73:18)
    at processHooks.call.then.hookObject (/Users/koraniar/GitHub/Vtul/vtul-api/node_modules/@feathersjs/feathers/lib/hooks/index.js:56:27)
error: Unhandled Rejection at: Promise  Promise {
  <rejected> TypeError: Cannot read property 'id' of undefined
    at sendResetPwd (/Users/koraniar/GitHub/Vtul/vtul-api/node_modules/feathers-authentication-management/lib/sendResetPwd.js:21:27)
    at Object.create (/Users/koraniar/GitHub/Vtul/vtul-api/node_modules/feathers-authentication-management/lib/service.js:73:18)
    at processHooks.call.then.hookObject (/Users/koraniar/GitHub/Vtul/vtul-api/node_modules/@feathersjs/feathers/lib/hooks/index.js:56:27) } message=Cannot read property 'id' of undefined, stack=TypeError: Cannot read property 'id' of undefined
    at sendResetPwd (/Users/koraniar/GitHub/Vtul/vtul-api/node_modules/feathers-authentication-management/lib/sendResetPwd.js:21:27)
    at Object.create (/Users/koraniar/GitHub/Vtul/vtul-api/node_modules/feathers-authentication-management/lib/service.js:73:18)
    at processHooks.call.then.hookObject (/Users/koraniar/GitHub/Vtul/vtul-api/node_modules/@feathersjs/feathers/lib/hooks/index.js:56:27)
```

### System configuration

Tell us about the applicable parts of your setup.

**Module versions**:
"feathers-authentication-management": "^2.0.1",
"@feathersjs/feathers": "^3.1.7",
"@feathersjs/authentication": "^2.1.7",
"@feathersjs/authentication-jwt": "^2.0.5",
"@feathersjs/authentication-local": "^1.2.1",
"@feathersjs/configuration": "^1.0.2",

**NodeJS version**: 10.0.5

**Operating System**: OS X 10.13.6 & Windows 10 Build 1806

**Comment by eddyystop** [comment]
I'm confused because node_modules/feathers-authentication-management/lib/sendResetPwd.js:21:27) is https://github.com/feathers-plus/feathers-authentication-management/blob/7d5234b0953e38dec797b8246c1416b2efe0bf73/src/sendResetPwd.js#L21

Could you paste the code your module starts with?

**Comment by eddyystop** [comment]
BTW the repo is being rewrittem as authentication-local-management. Full details are posted to https://github.com/feathers-plus/authentication-local-management/blob/master/misc/upgrading.md

**Comment by sanmeetsingh** [comment]
@koraniar  talking about 
 const usersIdName = users.id;
in your repo its line number 19

**Comment by michael-roewin** [comment]
@sanmeetsingh Hi Sam, I also encountered this issue. I also thought there was an issue on the code but it turns out the code is Ok. 

I solved this by setting the correct service in the 
authManagement.service.js file.. 
`app.configure(authManagement({
  service: 'user',
  notifier,
  ...
});`

And also by sending the correct data to <yourHost>/authManagement
```json
{
    "action": "sendResetPwd",
    "value": {
        "email" "example@domain.com"
    }
}
```

**Comment by sanmeetsingh** [comment]
I will check this, 
Is this the complete statement

app.configure(authManagement({ service: 'user', notifier, ... });

If not please send the complete statement

And I will check this solution

**Comment by michael-roewin** [comment]
this is the entire code of my auth-management.service.js file

`// Initializes the `authManagement` service on path `/authManagement`
const authManagement = require('feathers-authentication-management');
const hooks = require('./auth-management.hooks');
const notifier = require('./notifier');

module.exports = function (app) {

  // Initialize our service with any options it requires
  app.configure(authManagement(notifier(app)));

  // Get our initialized service so that we can register hooks
  const service = app.service('authManagement');

  service.hooks(hooks);
};
`

Here's the code for the notifier,js
`/* eslint-disable no-unused-vars */
module.exports = function (app) {
  const { sender } = app.get('mailer');
  const subHost = 'localhost:8080/';

  function getLink(type, hash) {
    const url = `${subHost + type}?token=${hash}`;
    return url;
  }
  
  function sendEmail(email) {
    return app.service('mailer').create(email).then((result) => {
      // eslint-disable-next-line no-console
      console.log('Sent email', result);
    }).catch((err) => {
      // eslint-disable-next-line no-console
      console.error('Error sending email', err);
    });
  }

  return {
    notifier(type, user, notifierOptions) {
      let tokenLink;
      let email;
      switch (type) {
      case 'resendVerifySignup': // sending the user the verification email
        tokenLink = getLink('verify', user.verifyToken);
        email = {
          from: sender,
          to: user.email,
          subject: 'Verify Signup',
          html: tokenLink,
        };
        return sendEmail(email);

      case 'verifySignup': // confirming verification
        tokenLink = getLink('verify', user.verifyToken);
        email = {
          from: sender,
          to: user.email,
          subject: 'Confirm Signup',
          html: 'Thanks for verifying your email',
        };
        return sendEmail(email);

      case 'sendResetPwd':
        tokenLink = getLink('reset-password', user.resetToken);
        email = {
          from: sender,
          to: user.email,
          subject: 'Password Reset',
          html: tokenLink,
        };
        return sendEmail(email);

      case 'resetPwd':
        tokenLink = getLink('reset-password', user.resetToken);
        email = {
          from: sender,
          to: user.email,
          subject: 'Password Reset',
          html: 'Password changed succesfully',
        };
        return sendEmail(email);

      case 'passwordChange':
        email = {
          from: sender,
          to: user.email,
          subject: 'Password Change',
          html: 'Password Changed succesfully',
        };
        return sendEmail(email);

      case 'identityChange':
        tokenLink = getLink('verifyChanges', user.verifyToken);
        email = {
          from: sender,
          to: user.email,
          subject: 'Change Identity',
          html: tokenLink,
        };
        return sendEmail(email);

      default:
        break;
      }
    },
  };
};
`

**Comment by sanmeetsingh** [comment]
Thanks for reply , I will definitely check this solution .

**Comment by claustres** [comment]
This issue being old we close it as we are trying to give a fresh look, please reopen if required.
