### ISSUE TITLE
pwReset should not be case sensitive

### ISSUE THREAD

**Issue by cannc4** [feathers-plus/feathers-authentication-management#121]
### Steps to reproduce
query`resetPw` with an email
### Expected behavior
`email` prop in the data object should be lowercase
### Actual behavior
`email` prop in the data object is case sensitive hence fails the MongoDB user queries

**Comment by claustres** [comment]
It seems to me normal that email check is case sensitive because the specs says so:
```
RFC 5321 2.4. General Syntax Principles and Transaction Model

SMTP implementations MUST take care to preserve the case of mailbox local-parts. In particular, for some hosts, the user "smith" is different from the user "Smith".

Mailbox domains follow normal DNS rules and are hence not case sensitive
```

So this module should not assume that for your mail server "Smith" is similar to "smith", if so please convert upfront.
