### ISSUE TITLE
resendVerifySignup is not working 

### ISSUE THREAD

**Issue by gchokeen** [feathers-plus/feathers-authentication-management#125]
I just tried to resend the OTP using following api call, it returns 201 response, but never triggered OTP notifier.

> POST http://localhost:3030/authManagement 
> {"action":"resendVerifySignup","value":{"phone":"phone number"}}

## authManagement config
 **"identifyUserProps":["_id","phone"],
  "shortTokenLen":6,
  "shortTokenDigits":true,**

Thanks

**Comment by claustres** [comment]
This issue being old we close it as we are trying to give a fresh look, please reopen if required and provide as much information as possible to reproduce it.
