### ISSUE TITLE
check unique is not working with mongodb

### ISSUE THREAD

**Issue by alidplus** [feathers-plus/feathers-authentication-management#133]
when comparing a string **(ownId)** with a objectId (mongodb id) in the:
https://github.com/feathers-plus/feathers-authentication-management/blob/95e5801229adba72b69e2bc7a9eb507b280db8bc/src/check-unique.js#L27
items[0][usersServiceIdName] **is not equal in type with** ownId

**Comment by claustres** [comment]
Could you provide a use case or code sample ? This hook is expected to be called on the client side so that all values are strings, eg as a before create hook on the user service.

**Comment by claustres** [comment]
This operation is expected to be called on the front side so that you should not have an ObjectId but a string.
