### ISSUE TITLE
how to use forgotten password of feathers-authentication-management 

### ISSUE THREAD

**Issue by abdolrhman** [feathers-plus/feathers-authentication-management#134]
I just wanna use this package in only a rest way, providing API is there any docs for this, 
thank you,
also, I am stuck here
how Allow user to reset the password if not yet verified?
I tried,
```
app.configure(authentication)
  .configure(authManagement({
    isVerified: false
  }));
didnt work```

Thanks :))

**Comment by claustres** [comment]
To allow password reset while not verified use the following option when configuring the module: `skipIsVerifiedCheck: true`. I've just added it in the docs.

There is also a section about REST in the doc: https://github.com/feathers-plus/feathers-authentication-management/blob/master/docs.md#http-fetch.

**Comment by abdolrhman** [comment]
Thank you @claustres,
another question please,
do I need to configure anything so that I can use these services the package provide?
I mean the mail service or SMS service etc,
thanks again

**Comment by abdolrhman** [comment]
this is closed, would be great if you could answer the other question.

**Comment by claustres** [comment]
The package does not provide email/sms services per se, you should use the [`notifier`](https://github.com/feathers-plus/feathers-authentication-management/blob/master/docs.md#service) option to manage the link with third-party services providing such features.

**Comment by abdolrhman** [comment]
is there is an example for this, I wanna use forget password service, with just mail,
thanks @claustres

**Comment by claustres** [comment]
https://hackernoon.com/setting-up-email-verification-in-feathersjs-ce764907e4f2

**Comment by abdolrhman** [comment]
Thanks, buddy appreciated :))

**Comment by ajimiathul** [comment]
how is this skipIsVerifiedCheck implemented?

**Comment by abnerfsuniga** [comment]
@claustres  "if true (default) it is impossible to reset password if email is not verified." The default is **false**

**Comment by claustres** [comment]
Thanks, fixed in docs.
