### ISSUE TITLE
sendResetPassword operation does not await notifier call

### ISSUE THREAD

**Issue by claustres** [feathers-plus/feathers-authentication-management#151]
### Steps to reproduce

Perform a `sendResetPassword` operation with a notifier sending an email.

### Expected behavior

Notifier call should be awaited

### Actual behavior

Notifier call is not awaited => see https://github.com/feathers-plus/feathers-authentication-management/blob/master/src/send-reset-pwd.js#L30

### System configuration

**NodeJS version**: 12.16

**Operating System**: Windows

**Module Loader**: 3.0

**Comment by sam-kelly-dev** [comment]
Thanks!
