### ISSUE TITLE
mysql DataType for 'verifyChanges' in user item

### ISSUE THREAD

**Issue by DaniSchenk** [feathers-plus/feathers-authentication-management#44]
I am using [sequelize](https://github.com/feathersjs/feathers-sequelize) to store my users in a database and I'm not sure which [Data Type](http://docs.sequelizejs.com/manual/tutorial/models-definition.html#data-types) I should use for 'verifyChanges'. The docs suggest `verifyChanges: // an object (key-value map), e.g. { field: "value" }`, but I don't know how to accomplish that in mysql. Any experiences?

**Comment by eddyystop** [comment]
I don't have sequelize experience, but can you store it as JSON data?

**Comment by eddyystop** [comment]
ryan.wheale says
Postgres has support for JSON fields. Before that, it was not uncommon to store JSON in a TEXT field. ... Not sure if sequelize would stringify an object for you or throw an error.

You could use hooks to convert to-from JSON.

**Comment by eddyystop** [comment]
I assume we can close this now. Feel free to reopen the issue if there is more to discuss.

**Comment by OfekA** [comment]
Sequelize does throw an error when using a STRING or TEXT in MySQL: "string violation: verifyChanges cannot be an array or an object"

Maybe we should add an example hook to the docs or fix the issue?

**Comment by eddyystop** [comment]
I believe you have to make that field JSON in some databases. What would your example be?

**Comment by OfekA** [comment]
I didn't try to use a hook, so I don't have an example at the moment, but thought it's worth mentioning that an error is emitted and that it doesn't currently work as is with MySQL.

**Comment by eddyystop** [comment]
This may be useful for this issue https://www.npmjs.com/package/sequelize-json

**Comment by DaniSchenk** [comment]
I just used mongodb instead.

**Comment by eddyystop** [comment]
I don't have a better answer than "I believe you have to make that field JSON in some databases." as that's what some people reported doing.

**Comment by eddyystop** [comment]
This issue is further handled in the a-l-m rewrite of this repo. Full details at https://github.com/feathers-plus/authentication-local-management/blob/master/misc/upgrading.md

Please add any further comments in a-l-m.
