### ISSUE TITLE
Cast to [string] failed for value \"[{}]\" at path \"verifyChanges\"

### ISSUE THREAD

**Issue by sylvainlap** [feathers-plus/feathers-authentication-management#53]
In docs, it is said that `verifyChanges` is an array of string: `verifyChanges New values to apply on verification to some identifyUserProps (string array)`.

However, during the `addVerification` hook, `verifyChanges` is set to `{}`. Docs should be changed to say that `verifyChanges` is a JSON, not an Array.

**Comment by eddyystop** [comment]
verifyChanges had originally been an array, I forgot to change the docs when verifyChanges was enhanced.

This has been done in the a-l-m rewrite. Full details at https://github.com/feathers-plus/authentication-local-management/blob/master/misc/upgrading.md

Please add any comments in a-l-m.

**Comment by sikanth** [comment]
ValidationError: ticket_number: Cast to String failed for value "[ 
'MDL-RSC-106-H84EB' ]" at path "ticket_number"

**Comment by sikanth** [comment]
ValidationError: ticket_number: Cast to String failed for value "[ 
'MDL-RSC-106-H84EB' ]" at path "ticket_number" 

i have same problem can you guys help me
