### ISSUE TITLE
Rate Limit Authenticate and Reset Password Requests

### ISSUE THREAD

**Issue by codingfriend1** [feathers-plus/feathers-authentication-management#69]
Authentication requests are using bcrypt which uses a lot of CPU. This means someone could make several authentication requests and possibly earn a denial of service attack.

I suggest throttling how many reset password, login, sign up, and change password requests can be made in a period. Perhaps we allow 3 upfront, then for each consecutive one they must wait 5 minutes. I suppose we can set the limits based on ip address.

**Comment by eddyystop** [comment]
A PR with good tests would be favorably considered.

**Comment by mogadanez** [comment]
Probably it should be feature of main feathers for any service

**Comment by eddyystop** [comment]
I can't be everywhere. A PR is welcome.

**Comment by claustres** [comment]
IMHO this is typically a task to be tackled using an external tool such as a reverse proxy like [traefik.io](https://docs.traefik.io/configuration/commons/#rate-limiting). However I must confess it is still hard to easily find something that works natively with web sockets.

**Comment by eddyystop** [comment]
Thanks Luc. I think we can close this now.

**Comment by ricardopolo** [comment]
@claustres if you do that using traefik it will work for WS trafick or only HTTPS?
If is the second case I dont think is so much usefull.

Any advice?

**Comment by claustres** [comment]
Yes as far as I know traefik will only handle HTTPS since it does not know what information is on the wire with websockets. I have written something about that in Medium since I commented here: https://blog.feathersjs.com/feathersjs-in-production-password-policy-and-rate-limiting-32c9874dc563. It is a more general approach that does not require to manage this at module level.

**Comment by mroushdy** [comment]
any updates on this? I have a public API that sends an SMS and does some database calls. Rate limiting it would be really great

**Comment by OnnoGabriel** [comment]
I don't think that rate limiting should be part of this package. First of all, DOS attacks could/should be prevented on network/firewall level, not within the application. And second, rate limiting of login attempts/password resets can be accomplished with some lines in a hook ([see here a Gist of mine](https://gist.github.com/OnnoGabriel/c6935c40f458a498df42ef1fb257b173)) or using the more general approach described by @claustres (see above).
