### ISSUE TITLE
User info is not valid. (authManagement)

### ISSUE THREAD

**Issue by dottodot** [feathers-plus/feathers-authentication-management#73]
When doing a post request to `authManagement` with the following data

```
{
    "action": "sendResetPwd",
    "value": "me@example.com"
}
```

I get a response of `User info is not valid. (authManagement)` and I've no idea what is means in order to fix the issue.

**Comment by eddyystop** [comment]
The docs (https://docs.feathersjs.com/api/authentication/local-management.html#client) have
```text
// send forgotten password notification
authManagement.create({ action: 'sendResetPwd',
  value: identifyUser, // {email}, {token: verifyToken}
  notifierOptions, // options passed to options.notifier, e.g. {preferredComm: 'email'}
})
```

You need `value: { email: 'me@example.com' }`.

**Comment by dottodot** [comment]
OK I wasn't familiar with `{email}` translating to that.

**Comment by TruePatronus** [comment]
I have similar problem when I'm trying to use verifySignupShort action.
I'm making a request with Postman to '/authmanagement' with these data:
`{
	"action": "verifySignupShort",
	"value": {
		"user": {"id":"9591d3e6-2e8d-44c1-9315-c8b02ca1e339"},
		"token":"367596"
  }
}`

And i get this response:
`{
    "name": "BadRequest",
    "message": "User info is not valid. (authManagement)",
    "code": 400,
    "className": "bad-request",
    "data": {},
    "errors": {
        "$className": "badParams"
    }
}`

Am I doing something wrong?

**Comment by outluch** [comment]
> UPD: Sry, found a mistake. I hadn't specified 'identifyUserProps'
I have the same problem. Digging sourcecode told me that function `ensureObjPropsValid` checks received user for inclusion of props, that are build from `identifyUserProps`. But I thought this parameter purpose is to keep unique fields for user, not all props of user instance.
Was I wrong? Should I add all the props from my migration to this array when configuring authManagement?

**Comment by codenamezjames** [comment]
I was passing the whole context results and it wanted only the email
```
    // user after hook
    create: [
      context => {
        context.app.service('authManagement').create({ action: 'resendVerifySignup', value: {email: context.result.email} })
      },
      verifyHooks.removeVerification()
    ],
```
