### ISSUE TITLE
After resetting password user not able to login

### ISSUE THREAD

**Issue by slightlytrue** [feathers-plus/feathers-authentication-management#78]
I have successfully reset password with `resetPwdLong`. But when I try to login again, I get Invalid login.

```json
"feathers": "^2.1.7",
"feathers-authentication": "^1.2.7",
"feathers-authentication-hooks": "^0.1.4",
"feathers-authentication-jwt": "^0.3.2",
"feathers-authentication-local": "^0.4.4",
"feathers-authentication-management": "^1.0.0",
"feathers-authentication-oauth2": "^0.2.5",
```

**Comment by eddyystop** [comment]
Could you please provide more information?

**Comment by BohdanRusinka** [comment]
+1

**Comment by eddyystop** [comment]
Still waiting for more info on this.

**Comment by BohdanRusinka** [comment]
@eddyystop 
So, after sign up the user is created and can successfully log-in. Then he wants to reset password and gets a token in the email (working with postgreSQL). He makes a request to /authManagement route: 
{
  action: 'resetPwdLong',
  value: { token: '2___cdd0b37de161178e31102f00c226d6', password: '123' }
}
Everything is ok. User object is returned. Then trying to log-in again  - error
error:  NotAuthenticated: Invalid login
I've debugged auth library and found that password comparison doesn't match.
It could be a misspelling error, but it is very difficult to da that with 123 password :) 
Do you have any idea what can be wrong?

**Comment by eddyystop** [comment]
I would suspect the password is being hashed twice. The repo hashes it automatically. Could you check if you have a hook that hashes it a second time?

**Comment by BohdanRusinka** [comment]
@eddyystop yep, my bad, I've added one more hashing hook for a patch action. Thanks a lot!

**Comment by slightlytrue** [comment]
Sorry for not replying. I did like @BohdanRusinka have said, and that was the problem.

**Comment by eddyystop** [comment]
That is a common problem when using this repo.
