### ISSUE TITLE
how to pass hook data to the notifier

### ISSUE THREAD

**Issue by DelfsEngineering** [feathers-plus/feathers-authentication-management#82]
I have a unique situation where I am managing authentication for several subdomains from a single codebase. In my `notifier.js` code  I call an external API that handles the transactional communications. 

I want to be able to pass this external service the subdomain and / or anything else I inject with a hook.

Is there a way I can get access to the hook or pass in the subdomain data to the notifier?

**Comment by eddyystop** [comment]
The notifier is called with
```js
notifier(options.notifier, 'resendVerifySignup', user, notifierOptions)
```
The notifierOptions is passed from the call to the service
```js
authManagement.create({ notifierOptions: ... }
```
That would be the way to pass custom values to the notifier.

**Comment by DelfsEngineering** [comment]
Brilliant,  that solves that.
Cheers
