### ISSUE TITLE
Bad date format with SQL database

### ISSUE THREAD

**Issue by sylvainlap** [feathers-plus/feathers-authentication-management#86]
With SQL database (PostgreSQL), feathers-auth-management doest not work out of the box, because of the use of `Date.now()` instead of `new Date()`.

I got errors like this:
```
{
  "name": "BadRequest",
  "message": " date/time field value out of range: \"1516020161065\"",
  "code": 400,
  "className": "bad-request",
  "errors": {}
}
```

Maybe you should consider using `new Date()` instead of `Date.now()`, to use actual Date.

Regards.

**Comment by eric-burel** [comment]
Hi,
I got this error `error:  RequestError: Operand type clash: bigint is incompatible with date` when using the `date` type in SQL Server and `RequestError: Arithmetic overflow error converting expression to data type datetime.` when using the timestamp type or datetime type.

I am not used to SQL but I guess it is the same issue. Any worlaround yet?

**Comment by eddyystop** [comment]
These issues are handled by the conversionSql hook provided in the a-l-m rewrite. Full details are at https://github.com/feathers-plus/authentication-local-management/blob/master/misc/upgrading.md

Please make any further comments in a-l-m. Thanks.

**Comment by eddyystop** [comment]
Read this about coercing data types for Sequelize and Knex https://github.com/feathers-plus/authentication-local-management/blob/master/misc/upgrading.md

You can do so using a hook similar to this https://github.com/feathers-plus/authentication-local-management/blob/master/src/hooks/conversion-sql.js

**Comment by hashcutdev** [comment]
I realize this is a few years later but I ran into the same problem and have a simpler fix.
The above solution from @morenoh149 works but then the data is stored as an int rather than the proper datetime format. I'm using Objection, and it was easy to do the data conversion in the Objection model file thusly:

users.model.js:
```
...
class users extends Model {
    static get tableName() {
        return 'users';
    }

    static get jsonSchema() {
        return {
            type: 'object',
            required: ['password'],

            properties: {
                email: { type: ['string', 'null'] },
                password: 'string',

                auth0Id: { type: 'string' },

                googleId: { type: 'string' },

                facebookId: { type: 'string' },

                twitterId: { type: 'string' },
                isVerified: { type: 'boolean' },
                verifyToken: { type: 'string' },
                verifyExpires: { type: 'date' },
                verifyChanges: { type: 'object' },
                resetToken: { type: 'string' },
                resetExpires: { type: 'date' },
            },
        };
    }

    $beforeInsert() {
        // eslint-disable-next-line no-multi-assign
        this.createdAt = this.updatedAt = new Date().toISOString();
        if (typeof(this.resetExpires) === 'number') {
            this.resetExpires = new Date(this.resetExpires).toISOString();
        }
        if (typeof(this.verifyExpires) === 'number') {
            this.verifyExpires = new Date(this.verifyExpires).toISOString();
        }
    }

    $beforeUpdate() {
        this.updatedAt = new Date().toISOString();
        if (typeof(this.resetExpires) === 'number') {
            this.resetExpires = new Date(this.resetExpires).toISOString();
        }
        if (typeof(this.verifyExpires) === 'number') {
            this.verifyExpires = new Date(this.verifyExpires).toISOString();
        }
    }
}
...
```
The main part is the $beforeInsert and $beforeUpdate functions, which check to see if the verifyExpires or resetExpires fields are numbers, and then recasts them to the proper Date value. This works and leaves your postgresql database with the proper field types.
