### ISSUE TITLE
Possible user information leak: sendRestPwd action?

### ISSUE THREAD

**Issue by 00Freezy00** [feathers-plus/feathers-authentication-management#90]
### Steps to reproduce

After the user requests a forgotten password reset, If the email exists, feathers-authentication-management will give back full user detail. I know it can be filtered in after hooks, but shouldn't it be handled by the API?

Request Payload:
{"action":"sendResetPwd","value": {"email":"test4@tester.com"}}
Response:
{
    "id": "df832c2c-074e-11e8-9633-a7bceebbc262",
    "email": "test4@tester.com",
    "firstName": "test",
    "lastName": "test",
    "phoneNumber": "asdasdsad",
    "facebookId": null,
    "isVerified": true,
    "googleId": null
}

### Expected behavior
The response should be sent or user not found

### Actual behavior
Response containing user details

**Comment by eddyystop** [comment]
The email sender is under your control. Its responsoble for including only information you want in the email. All the user data is passed to it so you are never short of what you need.

**Comment by 00Freezy00** [comment]
Oh ok thanks for explaining it to me.
