### ISSUE TITLE
Update to latest feathers-hooks-common?

### ISSUE THREAD

**Issue by bitflower** [feathers-plus/feathers-authentication-management#94]
I'm getting 2 deprecated warnings and this module seems to be very much behind...
I could PR if you want? However I might not see all the dependencies etc....

```terminal
npm WARN deprecated feathers-errors@2.9.2: Feathers v3 is out and has moved to @feathersjs/errors. See https://docs.feathersjs.com/migrating.html for more information.
npm WARN deprecated feathers-hooks@2.1.2: Feathers v3 is out and this module has been integrated into Feathers core. See https://docs.feathersjs.com/migrating.html for more information.
npm WARN @case-os/server@0.1.0 No license field.

```

**Comment by eddyystop** [comment]
I would appreciate a PR. I plan to get back to this repo after writing the docs for the graphql adapter, and for the resolver generator for it. So I'm tied up on that for a month.

**Comment by eddyystop** [comment]
Done in https://github.com/feathers-plus/authentication-local-management rewrite.
