### ISSUE TITLE
Migration error from disallow external

### ISSUE THREAD

**Issue by Elminday** [feathers-plus/feathers-authentication-management#95]
https://github.com/feathersjs/feathers/issues/849

Was asked to repost this issue here.

After migration to feathers v3 we get error from Auth-management service.

Error: MethodNotAllowed(405): Provider 'socketio' can not call 'create'. (disableMethod)

We use commonHooks.disallow('external') for 'all' hooks.before.

Our service:

```
const authManagement = require('feathers-authentication-management');
const notifier = require('./notifier');
const configUser = require('../user/config');

module.exports = app => authManagement({
  notifier: notifier(app).notifier,
  service: configUser.namespace,
  identifyUserProps: ['username', 'email', 'phone'],
});
```

**Comment by Elminday** [comment]
@eddyystop maybe you may know anything about this, cause we are stuck.

**Comment by Elminday** [comment]
Okay I deleted disallow('external'), but now I have another issue.

`app.authenticate({ strategy: 'local', email, password })`
gives error:`'user' record in the database is missing field 'password'`

from `@feathersjs/authentication-client/lib/passport.js`
code line: `socket[emit]('authenticate', credentials, (error, data)`

and `app.authenticate('jwt')` gives error: `no 'auth' token`

In app file global.TYPE is 'SERVER' so we get storage null.

```
const storage = (global.TYPE === 'CLIENT') ? window.localStorage : null;
export function app() {
  
  if (instance) return instance;

  instance = feathers()
    .configure(socket(io(uri)))
    .configure(auth({ storage }));

  return instance;
}
```

**Comment by eddyystop** [comment]
Neither this repo nor its dependencies display a message containing `missing field`. Your problem should be elsewhere, possibly in your schema?

**Comment by Elminday** [comment]
`'user' record in the database is missing a 'password'` is the correct message. I think it is not from my code, although I might be wrong.

**Comment by marshallswain** [comment]
@Elminday make sure you're not removing the password for internal requests.

**Comment by Elminday** [comment]
@marshallswain while debugging in `passport.js` I see that credentials passed to `authenticate({ credentials }) have password entered. Or do you mean somewhere else the removal of password?

**Comment by Elminday** [comment]
Could it be related to the fact that I delete `commonHooks.disallow('external')` from before all hook of authManagement?

**Comment by marshallswain** [comment]
Did you find the line that throws that error, yet?

**Comment by Elminday** [comment]
@marshallswain LocalVerifier._comparePassword

**Comment by marshallswain** [comment]
Can you stick a breakpoint and follow the stack trace back?

**Comment by Elminday** [comment]
LocalVerifier is in @feathers/authentication-local dependency and my application tab doesn't find that file, but I will try somehow else.

**Comment by marshallswain** [comment]
Try opening it up from node_modules in your editor and adding a `debugger` statement.

**Comment by Elminday** [comment]
The problem was:

We had a private service `profile` which uses `user` schema. In `all` hooks we use `common.hooks.keep(....`.

Somehow when `LocalVerifier._comparePassword` tries to get password from `user` entity there are only the fields used in `keep` hook.

We removed keep hook and it works now.

**Comment by eddyystop** [comment]
Thanks for the update. This'll be something I'll ask when others run into issues. +1
