### ISSUE TITLE
can't login after change password

### ISSUE THREAD

**Issue by maulikkanani1** [feathers-plus/feathers-authentication-management#96]
### Expected behavior
When I call the `resetPwdLong` API with `token` in my postman with following detail.
`POST` `http://localhost:3030/authmanagement`

> {
>     "action":"resetPwdLong",
>     "value": {
>     	"token": "token",
>     	"password":"my new password"
>     }
> }

My password was changed successfully
After changing password successfully, I can not log in with a new password, and can't log in with the old password also.

i also try `resetPwdShort` method.
`POST` `http://localhost:3030/authmanagement`

> {
>     "action":"resetPwdShort",
>     "value": {
>     	"user": identifyUser, // identify user, e.g. {email: 'a@a.com'}. See options.identifyUserProps.,
>     	"token": "token",
>      	"password":"my new password"
>     }
> }

it's give me an following error:

> {
>     "name": "BadRequest",
>     "message": "Invalid token. Get for a new one. (authManagement)",
>     "code": 400,
>     "className": "bad-request",
>     "data": {},
>     "errors": {
>         "$className": "badParam"
>     }
> }

please, any one help me.

**Comment by eddyystop** [comment]
Do you have a hashPassword hook defined for on the user service? The package hashes the password itself, so if you also have a hashpassword hook that password is being hashed twice.

The hashPassword hook should only execute for other calls. There are 2 articles on Medium showing how to do this.

**Comment by maulikkanani1** [comment]
thank @eddyystop, I solve this issue. 
my mistake was in user hook I update my password twice:

1. patch: [`auth.hashPassword()`]
and 
2. commonHooks.iff(
      commonHooks.isProvider('external'), 
     hashPassword(),
),

**Comment by eddyystop** [comment]
No problem. That is the most common made.
