### ISSUE TITLE
Not able to verify user. Using provided client library

### ISSUE THREAD

**Issue by syz3r** [feathers-plus/feathers-authentication-management#97]
### Steps to reproduce
- use authManagement/lib/client
- Call authManagement.verifySignupLong called with token
 
### Expected behavior
Should update user model.

### Actual behavior
Giving error "An id must be provided to the 'patch' method"

On deeper inspection I found inside verifySignup function usersIdName and users.id is undefined which should be "_id". Also I couldn't find any property inside service object which gives ID field name.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**: 9.11.1

**Operating System**: Mac

**Browser Version**: Chrome

**React Native Version**:

**Module Loader**:

**Comment by syz3r** [comment]
[https://github.com/feathers-plus/feathers-authentication-management/issues/81](url)
[https://github.com/feathers-plus/feathers-authentication-management/issues/80](url)

it is working after removing these lines from client code

~~import authManagementService from 'feathers-authentication-management';~~
~~app.configure(authManagementService(options))~~
const authManagement = app.service('authManagement');

**Comment by syz3r** [comment]
That's awesome! waiting for the release..

**Comment by hauckwill** [comment]
Is there any way to fix this when using feathers-redux?

**Comment by eddyystop** [comment]
I think syz3r's change was introduced quite a while ago.

@greyivy, I would think you can use feathers-redux to make the same authManagement service call that the client functions do. If you have any comments please add them to https://github.com/feathers-plus/authentication-local-management/issues/3

Full details on the authenticate-local-managment rewrite are in https://github.com/feathers-plus/authentication-local-management/blob/master/misc/upgrading.md
