### ISSUE TITLE
how to setup 2FA

### ISSUE THREAD

**Issue by musicformellons** [feathers-plus/feathers-authentication-management#99]
I am a bit puzzled how to setup two-factor-authentication, i.e. on login you receive sms-code on mobile which you need to enter to login. Is that supposed to be done with 'verifyShortToken', 'resetShortToken'? Are there any examples maybe how to setup 2FA?

**Comment by WebbizAdmin** [comment]
Id like to know this two. An example by someone who has impelmented it with feathers local would be great.

**Comment by hcbh96** [comment]
@WebbizAdmin, @musicformellons  If you guys are still interested in this I can write up this weekend, I implemented shortcode auth using Twilio a couple of months ago and have been meaning to write a blog on it. Unfortunately, I'm 100 miles an hour this week but could put something together this weekend?

**Comment by eddyystop** [comment]
This repo is scheduled for some major work in the next few months. This would be a good time to suggest and describe notable enhancements.

**Comment by musicformellons** [comment]
@hcbh96 That would be great. I am particularly interested in a [TOTP](https://en.wikipedia.org/wiki/Time-based_One-time_Password_algorithm) solution. See also [this](https://github.com/feathersjs/authentication/issues/130).

**Comment by WebbizAdmin** [comment]
@hcbh96 that would be brilliant.  
@eddyystop Will current implementations of this be totally scrapped?

**Comment by hcbh96** [comment]
Ok, I'll have a loop this weekend @musicformellons @WebbizAdmin , @eddyystop, I've got a couple of recommendation which would make TDD far easier when using the feathers auth management, but one can work around them so it is ok atm. I'll post my thoughts this weekend as well should I post them to here https://github.com/feathers-plus/feathers-authentication-management/issues ?

**Comment by WebbizAdmin** [comment]
@hcbh96 Thanks a million for your time.

**Comment by eddyystop** [comment]
@hcbh96 I think in this case its best to keep the discussiob in [this] one place.

**Comment by eddyystop** [comment]
@WebbizAdmin The current repo is the 3rd rewrite already. Each major upgrade had a migration path from the previous version.

I expect the same for the next major upgrade. The repo name may change though now that its under feathers-plus.

**Comment by eddyystop** [comment]
Some info: https://medium.com/@hcbh96/the-how-and-why-of-2fa-using-twilio-and-feathers-js-simple-2fa-tutorial-e64a930a57a8

**Comment by eddyystop** [comment]
Moved to https://github.com/feathers-plus/authentication-local-management/issues/1
